### ISSUE TITLE
M1, python3.11 can not use paddleocr

### ISSUE THREAD

**Issue by Yezhj1** [PaddlePaddle/PaddleOCR#9325]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Mac M1, python==3.11.2
- 版本号/Version：Paddle：1.0.2  PaddleOCR：2.6.01
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "/Users/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/uitrace/cvlib/ocr_match.py", line 50, in init_env
    from paddleocr import PaddleOCR
  File "/Users/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/Users/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/paddleocr/paddleocr.py", line 34, in <module>
    from tools.infer import predict_system
  File "/Users/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/paddleocr/tools/infer/predict_system.py", line 31, in <module>
    import tools.infer.utility as utility
  File "/Users/.pyenv/versions/3.11-dev/lib/python3.11/site-packages/paddleocr/tools/infer/utility.py", line 24, in <module>
    from paddle import inference
ImportError: cannot import name 'inference' from 'paddle' (/Users/.pyenv/versions/3.11-dev/lib/python3.11/site-
```
In my mac, I get such error, and i have searched the [solution](https://stackoverflow.com/questions/71599769/importerror-cannot-import-name-inference-from-paddle), but I find paddlepaddle can not be installed in python==3.11.2, mac m1

**Comment by LDOUBLEV** [comment]
It is recommended to use python version less than 3.10

**Comment by Yezhj1** [comment]
Thanks for your replay. I want to konw, not urging you，when the release will support python3.11.

**Comment by LDOUBLEV** [comment]
emmmm....
There is currently no clear plan when to support python3.11

**Comment by frapercan** [comment]
PaddleOCR is working fine on python 3.10 unless it breaks loggin and shows deprecation warnings.

3.7 that is the suggested one is too outdated :/
